MediQuick/MediQuick.Web/Controllers/AdminController.cs
using MediQuick.Data.Enums;
using MediQuick.Data.Models;
using MediQuick.Services.Contracts;
using MediQuick.Web.Models;
using MediQuick.Web.Models.Enums;
using Microsoft.AspNetCore.Mvc;

namespace MediQuick.Web.Controllers
{
    public class AdminController : BaseController
    {
        private readonly IHospitalService hospitalService;
        private readonly IRoleService roleService;
        private readonly IAmbulanceService ambulanceService;

        public AdminController(IUserService userService,
                                IHospitalService hospitalService,
                                IRoleService roleService,
                                IAmbulanceService ambulanceService) : base(userService)
        {
            this.hospitalService = hospitalService;
            this.roleService = roleService;
            this.ambulanceService = ambulanceService;
        }

        [HttpGet]
        public IActionResult CreateUser(CreateUserModel model)
        {
            SetUpBaseModel(model);

            model.RoleIds = new List<int>();

            model.Hospitals = hospitalService.GetAllHospitals();

            if (!model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.Admin.ToString()) &&
                model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.HospitalAdmin.ToString()))
            {
                model.Roles = roleService.GetSpecificRoles(new List<RoleType>() { RoleType.AmbulanceDriver, RoleType.HospitalEmployee });
            }
            else
            {
                model.Roles = roleService.GetAllRoles();
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult CreateUserPost(CreateUserModel model)
        {
            SetUpBaseModel(model);

            if (model.Password != model.RepeatPassword)
            {
                model.Messages.Add(new Message("Password and Repeat password must match", MessageType.Error));
                return View("CreateUser", model);
            }

            try
            {

                User user = userService.CreateUser(model.Username,
                    model.Password,
                    model.HospitalId ?? (int)model.User.HospitalId,
                    model.RoleIds);

                List<Role> selectedRoles = model.RoleIds.Select(x => roleService.GetRoleById(x)).ToList();

                if (selectedRoles.Any(x => x.Name == RoleType.AmbulanceDriver.ToString()))
                {
                    ambulanceService.AssignAmbulance(user.Id, model.User.HospitalId ?? (int)model.HospitalId);
                }

                model.Messages.Add(new Message("User created successfully", MessageType.Success));

                model.Username = "";
                model.Password = "";
                model.RepeatPassword = "";
                model.RoleIds = new List<int>();
                model.HospitalId = 0;

                return View("CreateUser", model);
            }
            catch (ArgumentException e)
            {
                model.Messages.Add(new Message(e.Message, MessageType.Error));
                return View("CreateUser", model);
            }
        }

        [HttpGet]
        public IActionResult CreateHospital(CreateHospitalModel model)
        {
            SetUpBaseModel(model);


            return View(model);
        }

        [HttpPost]
        public IActionResult CreateHospitalPost(CreateHospitalModel model)
        {
            SetUpBaseModel(model);

            if (model.Latitude == 0 || model.Latitude == null || model.Longitude == 0 || model.Longitude == null)
            {
                model.Messages.Add(new Message("Please select valid Longtitute and Latitude", MessageType.Error));
                return View("CreateHospital", model);
            }

            if (String.IsNullOrEmpty(model.Name))
            {
                model.Messages.Add(new Message("Hospital name cannot be empty", MessageType.Error));
                return View("CreateHospital", model);
            }


            try
            {
                hospitalService.CreateHospital(model.Name, (decimal)model.Longitude, (decimal)model.Latitude);

                model.Messages.Add(new Message("Hospital created successfully", MessageType.Success));
                return View("CreateHospital", model);
            }
            catch (ArgumentException e)
            {
                model.Messages.Add(new Message(e.Message, MessageType.Error));
                return View("CreateHospital", model);
            }

        }


    }
}

MediQuick/MediQuick.Web/Controllers/AmbulanceController.cs
using MediQuick.Data.Enums;
using MediQuick.Services.Contracts;
using MediQuick.Web.Models;
using MediQuick.Web.Models.Enums;
using Microsoft.AspNetCore.Mvc;

namespace MediQuick.Web.Controllers
{
    public class AmbulanceController : BaseController
    {
        private readonly IAmbulanceService ambulanceService;

        public AmbulanceController(IUserService userService, IAmbulanceService ambulanceService) : base(userService)
        {
            this.ambulanceService = ambulanceService;
        }

        [HttpGet]
        public IActionResult AssignPatient(AssignPatientModel model)
        {
            SetUpBaseModel(model);

            model.Ambulance = ambulanceService.GetAmbulanceByUserId(model.User.Id);
            
            if (model.Ambulance.PatientId != null)
            {
                model.FirstName = model.Ambulance.Patient.FirstName;
                model.LastName = model.Ambulance.Patient.LastName;
                model.Status = model.Ambulance.Patient.Status;
                model.DateOfBirth = model.Ambulance.Patient.DateOfBirth;
                model.ExtraInfo = model.Ambulance.Patient.ExtraInfo;
                model.Sex = model.Ambulance.Patient.Sex;
                model.SocialSecurityNumber = model.Ambulance.Patient.SocialSecurityNumber;
            }

            return View(model);
        }


        [HttpPost]
        public IActionResult AssignPatientPost(AssignPatientModel model, string buttonValue)
        {
            SetUpBaseModel(model);

            if (model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.AmbulanceDriver.ToString()))
            {
                model.Ambulance = ambulanceService.GetAmbulanceByUserId(model.User.Id);
            }
            else
            {
                model.Ambulance = ambulanceService.GetAmbulanceById(model.AmbulanceId);
            }

            if (buttonValue == "AssignPatientPost")
            {
                

                try
                {
                    if (model.Ambulance.PatientId != null)
                    {
                        ambulanceService.RemoveAmbulancePatient(model.Ambulance.Id);


                        model.FirstName = "";
                        model.LastName = "";
                        model.SocialSecurityNumber = "";
                        model.Sex = "";
                        model.Status = "";
                        model.DateOfBirth = DateTime.Now;
                        model.ExtraInfo = "";

                        ModelState.Clear();

                        SetUpBaseModel(model);

                        model.Messages.Add(new Message("Patient was unassigned", MessageType.Success));
                        return View("AssignPatient", model);
                    }
                    else
                    {
                        ambulanceService.AssignPatientToAmbulance(
                            model.Ambulance.Id,
                            model.FirstName,
                            model.LastName,
                            model.SocialSecurityNumber,
                            model.Sex,
                            model.Status,
                            model.DateOfBirth,
                            model.ExtraInfo);

                        
                        
                        model.Messages.Add(new Message("Patient was assigned", MessageType.Success));
                        return View("AssignPatient", model);
                    }
                }
                catch (Exception)
                {
                    model = new AssignPatientModel();

                    model.Messages.Add(new Message("There was an error!", MessageType.Error));
                    return View("AssignPatient", model);
                }
            }
            else if(buttonValue == "UpdatePatientPost")
            {
                if (model.Ambulance.PatientId == null)
                {
                    model = new AssignPatientModel();

                    model.Messages.Add(new Message("Patient was not found", MessageType.Error));
                    return View("AssignPatient", model);
                }

                ambulanceService.UpdatePatientOfAmbulance(
                        model.Ambulance.Id,
                        model.FirstName,
                        model.LastName,
                        model.SocialSecurityNumber,
                        model.Sex,
                        model.Status,
                        model.DateOfBirth,
                        model.ExtraInfo);


                model.Messages.Add(new Message("Patient info was updated", MessageType.Success));
                return View("AssignPatient", model);
            }

            return View("AssignPatient", model);
        }

        public IActionResult ViewAmbulance(ViewAmbulanceModel model)
        {
            SetUpBaseModel(model);

            if (model.AmbulanceId == null)
            {
                return RedirectToAction("Index", "Home", new BaseModel());
            }

            model.Ambulance = ambulanceService.GetAmbulanceById((int)model.AmbulanceId);

            if (model.Ambulance == null)
            {
                return RedirectToAction("Index", "Home", new BaseModel());
            }

            if(!model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.Admin.ToString()))
            {
                if(model.User.HospitalId != model.Ambulance.DestinationHospitalId)
                {
                    return RedirectToAction("Index", "Home", new BaseModel());
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult AmbulanceInfoPartial(int? ambulanceId)
        {
            ViewAmbulanceModel model = new ViewAmbulanceModel();

            SetUpBaseModel(model);

            model.AmbulanceId = ambulanceId;

            if (model.AmbulanceId == null)
            {
                return RedirectToAction("Index", "Home", new BaseModel());
            }

            model.Ambulance = ambulanceService.GetAmbulanceById((int)model.AmbulanceId);

            if (model.Ambulance == null)
            {
                return RedirectToAction("Index", "Home", new BaseModel());
            }

            if (!model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.Admin.ToString()))
            {
                if (model.User.HospitalId != model.Ambulance.DestinationHospitalId)
                {
                    return RedirectToAction("Index", "Home", new BaseModel());
                }
            }

            return PartialView("_AmbulanceInfoPartial", model);
        }
    }
}

MediQuick/MediQuick.Web/Controllers/HospitalController.cs
using MediQuick.Data.Enums;
using MediQuick.Data.Models;
using MediQuick.Services.Contracts;
using MediQuick.Web.Models;
using MediQuick.Web.Models.Enums;
using Microsoft.AspNetCore.Mvc;

namespace MediQuick.Web.Controllers
{
    public class HospitalController : BaseController
    {
        private readonly IAmbulanceService ambulanceService;

        public HospitalController(IUserService userService, IAmbulanceService ambulanceService) : base(userService)
        {
            this.ambulanceService = ambulanceService;
        }


        [HttpGet]
        public IActionResult ViewHospitalAmbulances(ViewHospitalAmbulancesModel model)
        {
            SetUpBaseModel(model);

            if (!model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.Admin.ToString()) &&
                (model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.HospitalEmployee.ToString()) ||
                 model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.HospitalAdmin.ToString())))
            {
                model.HospitalId = model.User.HospitalId;
            }

            List<Ambulance> ambulances = ambulanceService.GetAllAmbulancesFromHospital((int)model.HospitalId);

            model.AmbulanceStatuses = ambulances
                .Select(x => new AmbulanceStatus(x.User.Name, !(x.PatientId == null), x.Id))
                .ToList();

            return View(model);
        }
    }
}

MediQuick/MediQuick.Web/Controllers/UserController.cs
using MediQuick.Services.Contracts;
using MediQuick.Web.Models;
using MediQuick.Web.Models.Enums;
using Microsoft.AspNetCore.Mvc;

namespace MediQuick.Web.Controllers
{
    public class UserController : BaseController
    {
        public UserController(IUserService userService) : base(userService)
        {
        }

        [HttpGet("User/Login")]
        public IActionResult LoginView(LoginModel loginModel)
        {
            SetUpBaseModel(loginModel);
            return View("LoginView", loginModel);
        }

        [HttpGet]
        public IActionResult Logout(BaseModel model)
        {
            Response.Cookies.Delete("username");
            Response.Cookies.Delete("password");

            return RedirectToAction("Index", "Home", new BaseModel());
        }

        [HttpPost]
        public IActionResult LoginUser(LoginModel model)
        {
            SetUpBaseModel(model);

            try
            {
                userService.LoginUser(model.Username, model.Password);

                CookieOptions cookieOptions = new CookieOptions();
                cookieOptions.Expires = DateTime.UtcNow.AddDays(30);
                cookieOptions.Path = "/";

                Response.Cookies.Append("username", model.Username, cookieOptions);
                Response.Cookies.Append("password", model.Password, cookieOptions);

                return RedirectToAction("Index", "Home", new BaseModel());
            }
            catch(Exception ex)
            {
                model.Password = null;

                model.Messages.Add(new Message(ex.Message, MessageType.Error));

                return View("LoginView", model);
            }
        }
    }
}

MediQuick/MediQuick.Web/Views/Shared/_Layout.cshtml
@using MediQuick.Data.Enums
@model MediQuick.Web.Models.BaseModel

<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript">

        @if(!MediQuick.Web.Controllers.BaseController.IsAuthorised(Model))
        {
            @:window.location.href = "@Url.Action("Login","User")";
        }
    </script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediQuick</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MediQuick.Web.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        $(function() {
            toastr.options = {
              "closeButton": true,
              "debug": false,
              "newestOnTop": false,
              "progressBar": true,
              "positionClass": "toast-top-right",
              "preventDuplicates": false,
              "onclick": null,
              "showDuration": "300",
              "hideDuration": "1000",
              "timeOut": "5000",
              "extendedTimeOut": "1000",
              "showEasing": "swing",
              "hideEasing": "linear",
              "showMethod": "fadeIn",
              "hideMethod": "fadeOut"
            }

            @if(Model != null && Model.User != null && Model.User.UsersRoles != null &&
                Model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.AmbulanceDriver.ToString()))
            {
                @:startUpdatingLocation();
            }

            @if (Model.Messages != null)
            {
                foreach (var message in Model.Messages)
                {
                    @:toastr["@message.Type.ToString().ToLower()"]("@message.Text");
                }
            }
        })
        
    </script>
</head>
<body>
    <header>
        <div class="topnav">
            <a class="active" href="@Url.Action("Index", "Home")">Home</a>
            <a href="@Url.Action("About", "Home")">About</a>

            @if(Model != null && Model.User != null && Model.User.UsersRoles != null &&
                Model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.Admin.ToString()))
            {
                    <a b-e1ocawbhh6 asp-area="" asp-controller="Admin" asp-action="CreateUser">Create User</a>

            }

            @if(Model != null && Model.User != null && Model.User.UsersRoles != null &&
                Model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.Admin.ToString()))
            {
                    <a b-e1ocawbhh6 asp-area="" asp-controller="Admin" asp-action="CreateHospital">Create Hospital</a>

            }

            @if(Model != null && Model.User != null && Model.User.UsersRoles != null &&
                Model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.HospitalAdmin.ToString()))
            {
                <a b-e1ocawbhh6 asp-area="" asp-controller="Admin" asp-action="CreateUser">Register Employee</a>

                
            }

            @if(Model != null && Model.User != null && Model.User.UsersRoles != null &&
                (Model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.HospitalEmployee.ToString()) || 
                 Model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.HospitalAdmin.ToString())))
            {
                <a b-e1ocawbhh6 asp-area="" asp-controller="Hospital" asp-action="ViewHospitalAmbulances">View Ambulances</a>
            }

            @if(Model != null && Model.User != null && Model.User.UsersRoles != null &&
                (Model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.Admin.ToString()) || 
                 Model.User.UsersRoles.Select(x => x.Role.Name).Contains(RoleType.AmbulanceDriver.ToString())))
            {
                <a b-e1ocawbhh6 asp-area="" asp-controller="Ambulance" asp-action="AssignPatient">Patient</a>
            }

            @if((Model != null && Model.User == null) || Model == null )
            {
                <div class="login-container round-corners">
                    <a class="round-corners"  b-e1ocawbhh6 asp-area="" asp-controller="User" asp-action="Login">Log in</a>
                </div>
            }

            @if(Model != null && Model.User != null)
            {
                <div class="login-container round-corners">
                    <a class="round-corners"  b-e1ocawbhh6 >Logged in as @Model.User.UsersRoles.FirstOrDefault().Role.Name</a>
                    <a class="round-corners"  b-e1ocawbhh6 asp-area="" asp-controller="User" asp-action="Logout">Log out</a>
                </div>
            }

            <div class="login-container round-corners">
                 <img id="mediquick-logo" src="~/images/MediQuick.png"></img>
            </div>
            
        </div>
    </header>
    <div id="page-container" class="container">
        <main id="content-wrap" role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>